In [13]:
import pandas as pd
import json
import matplotlib.pyplot as plt
from collections import Counter

In [14]:
df = pd.read_csv("./Archaea_table.tsv", sep="\t")
df.head()

,MSDBID,OrganismName,CommonName,TaxID,Strain,Kingdom,Group,SubGroup,Size,GC,Annotation,AssemblyLevel,Source,Build,FilePrefix
0,MSDBG000175,Acidianus brierleyi,NaN,41673,strain=DSM 1651,Archaea,TACK group,Crenarchaeota,2.947,31.90,Y,Complete Genome,RefSeq,ASM320183v1,GCF_003201835.1_ASM320183v1
1,MSDBG000184,Acidiplasma aeolicum,NaN,507754,strain=VT,Archaea,Euryarchaeota,Diaforarchaea group,1.779,33.98,Y,Contig,RefSeq,ASM140294v1,GCF_001402945.1_ASM140294v1
2,MSDBG000185,Acidiplasma cupricumulans,NaN,312540,strain=BH2,Archaea,Euryarchaeota,Diaforarchaea group,1.731,34.17,Y,Contig,RefSeq,ASM140293v1,GCF_001402935.1_ASM140293v1
3,MSDBG000464,Aeropyrum pernix,NaN,56636,strain=YK1-12-2013,Archaea,TACK group,Crenarchaeota,1.601,56.48,Y,Scaffold,RefSeq,ASM432357v1,GCF_004323575.1_ASM432357v1
4,MSDBG000841,Archaeoglobus fulgidus,NaN,2234,NaN,Archaea,Euryarchaeota,Archaeoglobi,2.037,48.75,Y,Contig,RefSeq,ASM90006976v1,GCF_900069765.1_ASM90006976v1

In [15]:
df.shape

(1554, 15)

In [22]:
df1 = pd.read_csv("/home/ccmb/Desktop/SSRs_Prokaryotes_Analysis/Jupyter_Notebook/Descriptive_stats/Archeae_Datasetv1.tsv", sep="\t")
df1.head(20)

,Unnamed: 0,Unnamed: 0.1,file_name,Kingdom,Group,SubGroup,Organism_name,Genome_size,GC%,Total_repeats,TotalRepBases,Assembly_level,Assembly_name,coded_Assembly,Genome_size(mb),Total_repeats(mb),TotalRepBases(mb)
0,0,0,GCF_002287175.1_ASM228717v1,Archaea,Euryarchaeota,Methanomada group,Methanobacterium bryantii,3466370.0,33.19,2860.0,35950.0,Contig,ASM228717v1,1.0,3.466370,0.825071,10.371080
1,1,1,GCF_001458655.1_Mb9,Archaea,Euryarchaeota,Methanomada group,Methanobacterium formicicum,2494510.0,41.14,1710.0,21513.0,Complete Genome,Mb9,4.0,2.494510,0.685505,8.624139
2,2,2,GCF_002813085.1_ASM281308v1,Archaea,Euryarchaeota,Methanomada group,Methanobrevibacter smithii,1805545.0,31.15,1687.0,21231.0,Complete Genome,ASM281308v1,4.0,1.805545,0.934344,11.758776
3,3,3,GCF_001889405.1_ASM188940v1,Archaea,Euryarchaeota,Stenosarchaea group,Methanohalophilus halophilus,2022959.0,42.40,1060.0,13231.0,Complete Genome,ASM188940v1,4.0,2.022959,0.523985,6.540419
4,4,4,GCF_017875395.1_ASM1787539v1,Archaea,Euryarchaeota,Methanomada group,Methanococcus voltae,1899827.0,29.02,2549.0,34277.0,Contig,ASM1787539v1,1.0,1.899827,1.341701,18.042169
5,5,5,GCF_001571405.1_ASM157140v1,Archaea,Euryarchaeota,Stenosarchaea group,Methanoculleus thermophilus,2223235.0,59.32,1502.0,18781.0,Contig,ASM157140v1,1.0,2.223235,0.675592,8.447600
6,6,6,GCF_019263745.1_ASM1926374v1,Archaea,Euryarchaeota,Stenosarchaea group,Methanospirillum hungatei,3393136.0,42.21,1615.0,20151.0,Complete Genome,ASM1926374v1,4.0,3.393136,0.475961,5.938754
7,7,7,GCF_019669945.1_ASM1966994v1,Archaea,Euryarchaeota,Stenosarchaea group,Methanosarcina mazei,4417125.0,41.22,2629.0,33974.0,Complete Genome,ASM1966994v1,4.0,4.417125,0.595184,7.691428
8,8,29886,MSDBG021724,Archaea,Euryarchaeota,Stenosarchaea group,Methanosarcina thermophila,3194059.0,41.17,1767.0,22112.0,Complete Genome,ASM358460v1,4.0,3.194059,0.553215,6.922853
9,9,9,GCF_000765475.1_Mmet_Version1,Archaea,Euryarchaeota,Stenosarchaea group,Methanococcoides methylutens,2508511.0,42.50,1444.0,18540.0,Contig,Mmet_Version1,1.0,2.508511,0.575640,7.390839
10,10,25259,MSDBG010900,Archaea,Euryarchaeota,Archaeoglobi,Archaeoglobus fulgidus,2037571.0,48.84,1081.0,13532.0,Contig,ASM150874v1,1.0,2.037571,0.530534,6.641241
11,11,11,GCF_004799605.1_ASM479960v1,Archaea,Euryarchaeota,Stenosarchaea group,Halobacterium salinarum,2429680.0,66.28,2561.0,32577.0,Complete Genome,ASM479960v1,4.0,2.429680,1.054048,13.407938
12,12,12,GCF_018420015.1_ASM1842001v1,Archaea,Euryarchaeota,Stenosarchaea group,Haloferax volcanii,3940152.0,65.60,4867.0,62453.0,Contig,ASM1842001v1,1.0,3.940152,1.235232,15.850404
13,13,13,GCF_002215285.1_ASM221528v1,Archaea,Euryarchaeota,Stenosarchaea group,Halorubrum lacusprofundi,3278551.0,65.39,3681.0,46693.0,Scaffold,ASM221528v1,2.0,3.278551,1.122752,14.241962
14,14,14,GCF_000700025.1_ASM70002v2,Archaea,Euryarchaeota,Stenosarchaea group,Halorubrum saccharovorum,3282373.0,66.48,3997.0,50771.0,Contig,ASM70002v2,1.0,3.282373,1.217717,15.467773
15,15,15,GCF_900064395.1_ASM90006439v1,Archaea,Euryarchaeota,Thermococci,Thermococcus litoralis,2168485.0,43.20,1106.0,13822.0,Contig,ASM90006439v1,1.0,2.168485,0.510034,6.374035
16,16,16,GCF_009729015.1_ASM972901v1,Archaea,TACK group,Crenarchaeota,Acidianus ambivalens,2252027.0,34.23,1466.0,18312.0,Complete Genome,ASM972901v1,4.0,2.252027,0.650969,8.131341
17,17,17,GCF_002215485.1_ASM221548v1,Archaea,TACK group,Crenarchaeota,Sulfolobus acidocaldarius,2286709.0,36.76,1335.0,16681.0,Complete Genome,ASM221548v1,4.0,2.286709,0.583808,7.294763
18,18,18,GCF_019175305.1_ASM1917530v1,Archaea,TACK group,Crenarchaeota,Saccharolobus shibatae,2791785.0,35.64,1703.0,21327.0,Complete Genome,ASM1917530v1,4.0,2.791785,0.610004,7.639199
19,19,19,GCF_900079115.1_SSOP1,Archaea,TACK group,Crenarchaeota,Saccharolobus solfataricus,3034024.0,35.84,1907.0,23806.0,Complete Genome,SSOP1,4.0,3.034024,0.628538,7.846345

In [81]:
rclass_rank = {}

In [41]:
dff = pd.read_csv("/home/ccmb/Desktop/SSRs_Prokaryotes_Analysis/Jupyter_Notebook/Descriptive_stats/FinalArchaea_rankingDataset1.tsv", sep = "\t")

dff.head()

,subgroup,A,AAAAAC,AAAAAG,AAAAAT,AAAAC,AAAACC,AAAACG,AAAACT,AAAAG,...,CCCG,CCCGCG,CCCGG,CCCGGG,CCG,CCGCG,CCGCGG,CCGG,CCGGCG,CG
0,Stenosarchaea group,-2,3,3,3,-2,-2,-2,-2,3,...,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2
1,Archaeoglobi,-2,1,3,3,-2,-2,-2,-2,1,...,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2
2,Methanomada group,-2,-2,1,3,-2,-2,-2,-2,-2,...,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2
3,Stenosarchaea group,-2,-2,-2,-2,-2,-2,-2,-2,-2,...,-2,1,0,-2,2,0,1,-2,-2,-2
4,Nanoarchaeota,-2,-2,3,3,-2,-2,-2,2,3,...,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2

In [91]:
df1.shape

(2110, 17)

In [96]:
df1.groupby(['SubGroup']).count()

,Unnamed: 0,Unnamed: 0.1,file_name,Kingdom,Group,Organism_name,Genome_size,GC%,Total_repeats,TotalRepBases,Assembly_level,Assembly_name,coded_Assembly,Genome_size(mb),Total_repeats(mb),TotalRepBases(mb)
SubGroup,,,,,,,,,,,,,,,,
Archaeoglobi,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
Candidatus Aenigmarchaeota,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15
Candidatus Bathyarchaeota,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42
Candidatus Diapherotrites,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12
Candidatus Marsarchaeota,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15
Candidatus Micrarchaeota,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35
Candidatus Pacearchaeota,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41
Candidatus Parvarchaeota,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12
Candidatus Woesearchaeota,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38
Candidatus Wukongarchaeota,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45
Crenarchaeota,163,163,163,163,163,163,163,163,163,163,163,163,163,163,163,163
Diaforarchaea group,395,395,395,395,395,395,395,395,395,395,395,395,395,395,395,395
Methanomada group,123,123,123,123,123,123,123,123,123,123,123,123,123,123,123,123
Nanoarchaeota,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
Stenosarchaea group,760,760,760,760,760,760,759,759,759,759,759,759,759,759,759,759
Thaumarchaeota,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115,115
Thermococci,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74
Thermoplasmata,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
unclassified Archaea (miscellaneous),64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
unclassified Euryarchaeota,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113,113